services:
  site1:
    image: nginx:alpine
    container_name: site1
    volumes:
      - ./site1/index.html:/usr/share/nginx/html/index.html:ro

  site2:
    image: nginx:alpine
    container_name: site2
    volumes:
      - ./site2/index.html:/usr/share/nginx/html/index.html:ro

  reverseproxy:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - site1
      - site2
